import './strategy/strategy';
import './template-method/template-method';
import './visitor/visitor';
import './observer/observer';
import './state/state';
import './iterator/iterator';
import './chain-of-command/chain-of-command';
import './сommand/сommand';
import './memento/memento';
